#define MPU_I2C_ADDRESS 0xD0
#define MPU_SMPLRT_DIV 0x19
#define MPU_CONFIG 0x1a
#define MPU_GYRO_CONFIG 0x1b
#define MPU_ACCEL_CONFIG 0x1c
#define MPU_FIFO_EN 0x23

#define MPU_ACCEL_XOUT_H 0x3b
#define MPU_ACCEL_XOUT_L 0x3c
#define MPU_ACCEL_YOUT_H 0x3d
#define MPU_ACCEL_YOUT_L 0x3e
#define MPU_ACCEL_ZOUT_H 0x3f
#define MPU_ACCEL_ZOUT_L 0x40

#define MPU_GYRO_XOUT_H 0x43
#define MPU_GYRO_XOUT_L 0x44
#define MPU_GYRO_YOUT_H 0x45
#define MPU_GYRO_YOUT_L 0x46
#define MPU_GYRO_ZOUT_H 0x47
#define MPU_GYRO_ZOUT_L 0x48

#define MPU_USER_CTRL 0x6a
#define MPU_PWR_MGMT_1 0x6B
#define MPU_WHO_AM_I 0x75
